env:
  global:
    - CC_TEST_REPORTER_ID=1929a6e27988524fc1e89e1ad35458a4f40866bc8451879cf99a07315918a912

language: ruby

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - bundle exec rspec

after_script:
  - ./cc-test-reporter after-build -t lcov --exit-code $TRAVIS_TEST_RESULT